# The Docker image that will be used to build your app
image: alpine:latest

# Functions that should be executed before the build script is run
before_script: []

variables:
  GIT_DEPTH: 1  # Shallow clone for faster checkouts

pages:
  script:
    - echo "Deploying to GitLab Pages..."
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
    expire_in: 1 week  # Artifacts will be deleted after 1 week
  cache:
    paths:
      - public
    key: ${CI_COMMIT_REF_SLUG}
  interruptible: true  # Allows canceling redundant pipelines
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
