version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./python:/app
    environment:
      - GITLAB_USERNAME=${GITLAB_USERNAME:-gitlab+deploy-token-6867370}
      - GITLAB_TOKEN=${GITLAB_TOKEN:-gldt-kcGncapSUAPx9BPW4cxC}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: my-html-server
    ports:
      - "8080:80"
    volumes:
      - ./src/templates:/usr/share/nginx/html
    depends_on:
      - backend
